
package com.training;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NumberToTextImplService", targetNamespace = "http://services.training.com/", wsdlLocation = "http://localhost:9000/weather?wsdl")
public class NumberToTextImplService
    extends Service
{

    private final static URL NUMBERTOTEXTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NUMBERTOTEXTIMPLSERVICE_EXCEPTION;
    private final static QName NUMBERTOTEXTIMPLSERVICE_QNAME = new QName("http://services.training.com/", "NumberToTextImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUMBERTOTEXTIMPLSERVICE_WSDL_LOCATION = url;
        NUMBERTOTEXTIMPLSERVICE_EXCEPTION = e;
    }

    public NumberToTextImplService() {
        super(__getWsdlLocation(), NUMBERTOTEXTIMPLSERVICE_QNAME);
    }

    public NumberToTextImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUMBERTOTEXTIMPLSERVICE_QNAME, features);
    }

    public NumberToTextImplService(URL wsdlLocation) {
        super(wsdlLocation, NUMBERTOTEXTIMPLSERVICE_QNAME);
    }

    public NumberToTextImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUMBERTOTEXTIMPLSERVICE_QNAME, features);
    }

    public NumberToTextImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NumberToTextImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NumberToTextService
     */
    @WebEndpoint(name = "NumberToTextImplPort")
    public NumberToTextService getNumberToTextImplPort() {
        return super.getPort(new QName("http://services.training.com/", "NumberToTextImplPort"), NumberToTextService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NumberToTextService
     */
    @WebEndpoint(name = "NumberToTextImplPort")
    public NumberToTextService getNumberToTextImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.training.com/", "NumberToTextImplPort"), NumberToTextService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUMBERTOTEXTIMPLSERVICE_EXCEPTION!= null) {
            throw NUMBERTOTEXTIMPLSERVICE_EXCEPTION;
        }
        return NUMBERTOTEXTIMPLSERVICE_WSDL_LOCATION;
    }

}
